exports.proyectos = [{
    "id": 1,
    "year": 2021,
    "nombre": "Habilitación de Enlace de 100G con StackPack",
    "estado": 0,
    "avance": 0,
    "descripcion": "Habilitar peering con STACKPACK para intercambio de Tráfico",
    "time_begin": "2021-03-15 19:00:00",
    "time_end": "2021-06-27 19:00:00",
    // "url": "habilitacion-de-enlace-de-100g-con-stackpack-T0Vk-MrWw",
    "createdAt": Date.now(),
    "updatedAt": Date.now(),
    "tipoproyectoId": 5,
    "estadosproyectoId": null
  },
  {
    "id": 2,
    "year": 2021,
    "nombre": "Ampliaciones de Capacidad en Core MPLS - 2021",
    "estado": 0,
    "descripcion": "Ampliar capacidad a nivel Nacional",
    "time_begin": "2021-02-01 19:00:00",
    "time_end": "2021-05-27 19:00:00",
    // "url": "ampliaciones-de-capacidad-en-corex2fmpls-gSDLkoYby",
    "createdAt": Date.now(),
    "updatedAt": Date.now(),
    "tipoproyectoId": 1,
    "estadosproyectoId": null
  },
  {
    "id": 3,
    "year": 2021,
    "nombre": "Ampliación de Capacidad de TelcoCloud - 2021",
    "estado": 0,
    "descripcion": "Ampliación de Capacidad dentro del TelcoCloud y en el Core",
    "time_begin": "2021-02-21 19:00:00",
    "time_end": "2021-08-30 19:00:00",
    // "url": "trial-zte-u4SD30AvU",
    "createdAt": Date.now(),
    "updatedAt": Date.now(),
    "tipoproyectoId": 3,
    "estadosproyectoId": null
  },
  {
    "id": 4,
    "year": 2020,
    "nombre": "Instalación de AntiDDos de Huawei",
    "estado": 0,
    "descripcion": "Instalación de Solución DDoS de Huawei en Polo1 y VES",
    "time_begin": "2020-08-1 19:00:00",
    "time_end": "2021-05-15 19:00:00",
    // "url": "trial-zte-u4SD30AvU",
    "createdAt": Date.now(),
    "updatedAt": Date.now(),
    "tipoproyectoId": 5,
    "estadosproyectoId": null
  },
  {
    "id": 5,
    "year": 2021,
    "nombre": "Instalación de Equipamiento IPRAN - 2021",
    "estado": 0,
    "descripcion": "Instalación de equipos IPRAN para creacimiento de Servicios Móviles y Fijos",
    "time_begin": "2021-03-15 19:00:00",
    "time_end": "2021-12-30 19:00:00",
    // "url": "trial-zte-u4SD30AvU",
    "createdAt": Date.now(),
    "updatedAt": Date.now(),
    "tipoproyectoId": 5,
    "estadosproyectoId": null
  },
  {
    "id": 6,
    "year": 2021,
    "nombre": "Instalación de Servidores de Cache a nivel Nacional - 2021",
    "estado": 0,
    "descripcion": "Instalación de CDN de Facebook, Google, Netflix, TickTock y otros",
    "time_begin": "2021-03-15 19:00:00",
    "time_end": "2021-12-30 19:00:00",
    // "url": "trial-zte-u4SD30AvU",
    "createdAt": Date.now(),
    "updatedAt": Date.now(),
    "tipoproyectoId": 5,
    "estadosproyectoId": null
  }
]